In [54]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import openpyxl as xls

In [21]:
d = pd.read_excel("C:\\Users\\sande\\OneDrive\\Desktop\\DA project.xlsx")
df = pd.DataFrame(d)

In [23]:
df

,Retailer,Retailer ID,Invoice Date,Month,Year,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Walmart,1128299,2020-04-03,Apr,2020,Southeast,Florida,Orlando,Women's Apparel,103,218,2245,1257,Online
1,West Gear,1128299,2020-12-26,Dec,2020,South,Louisiana,New Orleans,Women's Apparel,103,163,1679,806,Online
2,Sports Direct,1197831,2020-02-18,Feb,2020,South,Alabama,Birmingham,Men's Street Footwear,10,700,7000,3150,Outlet
3,Sports Direct,1197831,2021-03-28,Mar,2021,South,Alabama,Birmingham,Women's Street Footwear,15,575,8625,3881,Outlet
4,Sports Direct,1197831,2021-02-16,Feb,2021,South,Alabama,Birmingham,Women's Street Footwear,15,475,7125,3206,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,Amazon,1185732,2021-02-20,Feb,2021,Northeast,Vermont,Burlington,Women's Street Footwear,45,81,365,171,Online
4995,Amazon,1185732,2020-08-04,Aug,2020,Northeast,Vermont,Burlington,Men's Apparel,58,81,470,235,Online
4996,West Gear,1185732,2021-06-04,Jun,2021,Northeast,Vermont,Burlington,Women's Apparel,71,81,575,305,Online
4997,West Gear,1185732,2020-04-26,Apr,2020,Northeast,Vermont,Burlington,Men's Athletic Footwear,55,81,446,258,Online
4998,Amazon,1185732,2020-01-24,Jan,2020,Northeast,Vermont,Burlington,Women's Athletic Footwear,56,81,454,204,Online

In [25]:
df.isnull().sum()

Retailer            0
Retailer ID         0
Invoice Date        2
Month               0
Year                0
Region              0
State               0
City                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Sales Method        0
dtype: int64

In [27]:
data = df.fillna(method='ffill')
data

C:\Users\sande\AppData\Local\Temp\ipykernel_10000\2343735486.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data = df.fillna(method='ffill')

,Retailer,Retailer ID,Invoice Date,Month,Year,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Sales Method
0,Walmart,1128299,2020-04-03,Apr,2020,Southeast,Florida,Orlando,Women's Apparel,103,218,2245,1257,Online
1,West Gear,1128299,2020-12-26,Dec,2020,South,Louisiana,New Orleans,Women's Apparel,103,163,1679,806,Online
2,Sports Direct,1197831,2020-02-18,Feb,2020,South,Alabama,Birmingham,Men's Street Footwear,10,700,7000,3150,Outlet
3,Sports Direct,1197831,2021-03-28,Mar,2021,South,Alabama,Birmingham,Women's Street Footwear,15,575,8625,3881,Outlet
4,Sports Direct,1197831,2021-02-16,Feb,2021,South,Alabama,Birmingham,Women's Street Footwear,15,475,7125,3206,Outlet
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4994,Amazon,1185732,2021-02-20,Feb,2021,Northeast,Vermont,Burlington,Women's Street Footwear,45,81,365,171,Online
4995,Amazon,1185732,2020-08-04,Aug,2020,Northeast,Vermont,Burlington,Men's Apparel,58,81,470,235,Online
4996,West Gear,1185732,2021-06-04,Jun,2021,Northeast,Vermont,Burlington,Women's Apparel,71,81,575,305,Online
4997,West Gear,1185732,2020-04-26,Apr,2020,Northeast,Vermont,Burlington,Men's Athletic Footwear,55,81,446,258,Online
4998,Amazon,1185732,2020-01-24,Jan,2020,Northeast,Vermont,Burlington,Women's Athletic Footwear,56,81,454,204,Online

In [29]:
data.isnull().sum()

Retailer            0
Retailer ID         0
Invoice Date        0
Month               0
Year                0
Region              0
State               0
City                0
Product             0
Price per Unit      0
Units Sold          0
Total Sales         0
Operating Profit    0
Sales Method        0
dtype: int64

In [31]:
data.to_excel("C:\\Users\\sande\\OneDrive\\Desktop\\DA_project.xlsx")